// Generated by gencpp from file panda_mover/ExecutionServiceRequest.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_EXECUTIONSERVICEREQUEST_H
#define PANDA_MOVER_MESSAGE_EXECUTIONSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <panda_mover/ListOfFloats.h>

namespace panda_mover
{
template <class ContainerAllocator>
struct ExecutionServiceRequest_
{
  typedef ExecutionServiceRequest_<ContainerAllocator> Type;

  ExecutionServiceRequest_()
    : joint_states()  {
    }
  ExecutionServiceRequest_(const ContainerAllocator& _alloc)
    : joint_states(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::panda_mover::ListOfFloats_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::panda_mover::ListOfFloats_<ContainerAllocator> >> _joint_states_type;
  _joint_states_type joint_states;





  typedef boost::shared_ptr< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutionServiceRequest_

typedef ::panda_mover::ExecutionServiceRequest_<std::allocator<void> > ExecutionServiceRequest;

typedef boost::shared_ptr< ::panda_mover::ExecutionServiceRequest > ExecutionServiceRequestPtr;
typedef boost::shared_ptr< ::panda_mover::ExecutionServiceRequest const> ExecutionServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator1> & lhs, const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_states == rhs.joint_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator1> & lhs, const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_mover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad64a8c77c8e0058db48fb69961d2443";
  }

  static const char* value(const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad64a8c77c8e0058ULL;
  static const uint64_t static_value2 = 0xdb48fb69961d2443ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_mover/ExecutionServiceRequest";
  }

  static const char* value(const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_mover/ListOfFloats[] joint_states\n"
"\n"
"================================================================================\n"
"MSG: panda_mover/ListOfFloats\n"
"float64[] list\n"
;
  }

  static const char* value(const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecutionServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_mover::ExecutionServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_mover::ExecutionServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_states[]" << std::endl;
    for (size_t i = 0; i < v.joint_states.size(); ++i)
    {
      s << indent << "  joint_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::panda_mover::ListOfFloats_<ContainerAllocator> >::stream(s, indent + "    ", v.joint_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_EXECUTIONSERVICEREQUEST_H
