// Generated by gencpp from file panda_mover/ExecutionService.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_EXECUTIONSERVICE_H
#define PANDA_MOVER_MESSAGE_EXECUTIONSERVICE_H

#include <ros/service_traits.h>


#include <panda_mover/ExecutionServiceRequest.h>
#include <panda_mover/ExecutionServiceResponse.h>


namespace panda_mover
{

struct ExecutionService
{

typedef ExecutionServiceRequest Request;
typedef ExecutionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecutionService
} // namespace panda_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_mover::ExecutionService > {
  static const char* value()
  {
    return "200ed2e45e29d7b67fa3d65a61af734d";
  }

  static const char* value(const ::panda_mover::ExecutionService&) { return value(); }
};

template<>
struct DataType< ::panda_mover::ExecutionService > {
  static const char* value()
  {
    return "panda_mover/ExecutionService";
  }

  static const char* value(const ::panda_mover::ExecutionService&) { return value(); }
};


// service_traits::MD5Sum< ::panda_mover::ExecutionServiceRequest> should match
// service_traits::MD5Sum< ::panda_mover::ExecutionService >
template<>
struct MD5Sum< ::panda_mover::ExecutionServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::ExecutionService >::value();
  }
  static const char* value(const ::panda_mover::ExecutionServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::ExecutionServiceRequest> should match
// service_traits::DataType< ::panda_mover::ExecutionService >
template<>
struct DataType< ::panda_mover::ExecutionServiceRequest>
{
  static const char* value()
  {
    return DataType< ::panda_mover::ExecutionService >::value();
  }
  static const char* value(const ::panda_mover::ExecutionServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_mover::ExecutionServiceResponse> should match
// service_traits::MD5Sum< ::panda_mover::ExecutionService >
template<>
struct MD5Sum< ::panda_mover::ExecutionServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::ExecutionService >::value();
  }
  static const char* value(const ::panda_mover::ExecutionServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::ExecutionServiceResponse> should match
// service_traits::DataType< ::panda_mover::ExecutionService >
template<>
struct DataType< ::panda_mover::ExecutionServiceResponse>
{
  static const char* value()
  {
    return DataType< ::panda_mover::ExecutionService >::value();
  }
  static const char* value(const ::panda_mover::ExecutionServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_EXECUTIONSERVICE_H
