// Generated by gencpp from file panda_mover/GetTrainingDataService.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_GETTRAININGDATASERVICE_H
#define PANDA_MOVER_MESSAGE_GETTRAININGDATASERVICE_H

#include <ros/service_traits.h>


#include <panda_mover/GetTrainingDataServiceRequest.h>
#include <panda_mover/GetTrainingDataServiceResponse.h>


namespace panda_mover
{

struct GetTrainingDataService
{

typedef GetTrainingDataServiceRequest Request;
typedef GetTrainingDataServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTrainingDataService
} // namespace panda_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_mover::GetTrainingDataService > {
  static const char* value()
  {
    return "a23732bf635c86b0cb4cf0b1248e70e9";
  }

  static const char* value(const ::panda_mover::GetTrainingDataService&) { return value(); }
};

template<>
struct DataType< ::panda_mover::GetTrainingDataService > {
  static const char* value()
  {
    return "panda_mover/GetTrainingDataService";
  }

  static const char* value(const ::panda_mover::GetTrainingDataService&) { return value(); }
};


// service_traits::MD5Sum< ::panda_mover::GetTrainingDataServiceRequest> should match
// service_traits::MD5Sum< ::panda_mover::GetTrainingDataService >
template<>
struct MD5Sum< ::panda_mover::GetTrainingDataServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::GetTrainingDataService >::value();
  }
  static const char* value(const ::panda_mover::GetTrainingDataServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::GetTrainingDataServiceRequest> should match
// service_traits::DataType< ::panda_mover::GetTrainingDataService >
template<>
struct DataType< ::panda_mover::GetTrainingDataServiceRequest>
{
  static const char* value()
  {
    return DataType< ::panda_mover::GetTrainingDataService >::value();
  }
  static const char* value(const ::panda_mover::GetTrainingDataServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_mover::GetTrainingDataServiceResponse> should match
// service_traits::MD5Sum< ::panda_mover::GetTrainingDataService >
template<>
struct MD5Sum< ::panda_mover::GetTrainingDataServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::GetTrainingDataService >::value();
  }
  static const char* value(const ::panda_mover::GetTrainingDataServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::GetTrainingDataServiceResponse> should match
// service_traits::DataType< ::panda_mover::GetTrainingDataService >
template<>
struct DataType< ::panda_mover::GetTrainingDataServiceResponse>
{
  static const char* value()
  {
    return DataType< ::panda_mover::GetTrainingDataService >::value();
  }
  static const char* value(const ::panda_mover::GetTrainingDataServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_GETTRAININGDATASERVICE_H
