// Generated by gencpp from file panda_mover/GripperServiceResponse.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_GRIPPERSERVICERESPONSE_H
#define PANDA_MOVER_MESSAGE_GRIPPERSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_mover
{
template <class ContainerAllocator>
struct GripperServiceResponse_
{
  typedef GripperServiceResponse_<ContainerAllocator> Type;

  GripperServiceResponse_()
    : output_msg()  {
    }
  GripperServiceResponse_(const ContainerAllocator& _alloc)
    : output_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _output_msg_type;
  _output_msg_type output_msg;





  typedef boost::shared_ptr< ::panda_mover::GripperServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_mover::GripperServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GripperServiceResponse_

typedef ::panda_mover::GripperServiceResponse_<std::allocator<void> > GripperServiceResponse;

typedef boost::shared_ptr< ::panda_mover::GripperServiceResponse > GripperServiceResponsePtr;
typedef boost::shared_ptr< ::panda_mover::GripperServiceResponse const> GripperServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_mover::GripperServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_mover::GripperServiceResponse_<ContainerAllocator1> & lhs, const ::panda_mover::GripperServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output_msg == rhs.output_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_mover::GripperServiceResponse_<ContainerAllocator1> & lhs, const ::panda_mover::GripperServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_mover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_mover::GripperServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_mover::GripperServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_mover::GripperServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef13bd7685401359f42466106b070713";
  }

  static const char* value(const ::panda_mover::GripperServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef13bd7685401359ULL;
  static const uint64_t static_value2 = 0xf42466106b070713ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_mover/GripperServiceResponse";
  }

  static const char* value(const ::panda_mover::GripperServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output_msg\n"
;
  }

  static const char* value(const ::panda_mover::GripperServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_mover::GripperServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_mover::GripperServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "output_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.output_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_GRIPPERSERVICERESPONSE_H
