// Generated by gencpp from file panda_mover/ListOfFloats.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_LISTOFFLOATS_H
#define PANDA_MOVER_MESSAGE_LISTOFFLOATS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panda_mover
{
template <class ContainerAllocator>
struct ListOfFloats_
{
  typedef ListOfFloats_<ContainerAllocator> Type;

  ListOfFloats_()
    : list()  {
    }
  ListOfFloats_(const ContainerAllocator& _alloc)
    : list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _list_type;
  _list_type list;





  typedef boost::shared_ptr< ::panda_mover::ListOfFloats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_mover::ListOfFloats_<ContainerAllocator> const> ConstPtr;

}; // struct ListOfFloats_

typedef ::panda_mover::ListOfFloats_<std::allocator<void> > ListOfFloats;

typedef boost::shared_ptr< ::panda_mover::ListOfFloats > ListOfFloatsPtr;
typedef boost::shared_ptr< ::panda_mover::ListOfFloats const> ListOfFloatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_mover::ListOfFloats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_mover::ListOfFloats_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_mover::ListOfFloats_<ContainerAllocator1> & lhs, const ::panda_mover::ListOfFloats_<ContainerAllocator2> & rhs)
{
  return lhs.list == rhs.list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_mover::ListOfFloats_<ContainerAllocator1> & lhs, const ::panda_mover::ListOfFloats_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_mover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_mover::ListOfFloats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_mover::ListOfFloats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_mover::ListOfFloats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_mover::ListOfFloats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_mover::ListOfFloats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_mover::ListOfFloats_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_mover::ListOfFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c927dcaf1d3ff0b9aa7fd844cd956a22";
  }

  static const char* value(const ::panda_mover::ListOfFloats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc927dcaf1d3ff0b9ULL;
  static const uint64_t static_value2 = 0xaa7fd844cd956a22ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_mover::ListOfFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_mover/ListOfFloats";
  }

  static const char* value(const ::panda_mover::ListOfFloats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_mover::ListOfFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] list\n"
;
  }

  static const char* value(const ::panda_mover::ListOfFloats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_mover::ListOfFloats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListOfFloats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_mover::ListOfFloats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_mover::ListOfFloats_<ContainerAllocator>& v)
  {
    s << indent << "list[]" << std::endl;
    for (size_t i = 0; i < v.list.size(); ++i)
    {
      s << indent << "  list[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_LISTOFFLOATS_H
