// Generated by gencpp from file panda_mover/PlannerService.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_PLANNERSERVICE_H
#define PANDA_MOVER_MESSAGE_PLANNERSERVICE_H

#include <ros/service_traits.h>


#include <panda_mover/PlannerServiceRequest.h>
#include <panda_mover/PlannerServiceResponse.h>


namespace panda_mover
{

struct PlannerService
{

typedef PlannerServiceRequest Request;
typedef PlannerServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlannerService
} // namespace panda_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_mover::PlannerService > {
  static const char* value()
  {
    return "a9d9e87f111d55827a268a07768a7199";
  }

  static const char* value(const ::panda_mover::PlannerService&) { return value(); }
};

template<>
struct DataType< ::panda_mover::PlannerService > {
  static const char* value()
  {
    return "panda_mover/PlannerService";
  }

  static const char* value(const ::panda_mover::PlannerService&) { return value(); }
};


// service_traits::MD5Sum< ::panda_mover::PlannerServiceRequest> should match
// service_traits::MD5Sum< ::panda_mover::PlannerService >
template<>
struct MD5Sum< ::panda_mover::PlannerServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::PlannerService >::value();
  }
  static const char* value(const ::panda_mover::PlannerServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::PlannerServiceRequest> should match
// service_traits::DataType< ::panda_mover::PlannerService >
template<>
struct DataType< ::panda_mover::PlannerServiceRequest>
{
  static const char* value()
  {
    return DataType< ::panda_mover::PlannerService >::value();
  }
  static const char* value(const ::panda_mover::PlannerServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_mover::PlannerServiceResponse> should match
// service_traits::MD5Sum< ::panda_mover::PlannerService >
template<>
struct MD5Sum< ::panda_mover::PlannerServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::PlannerService >::value();
  }
  static const char* value(const ::panda_mover::PlannerServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::PlannerServiceResponse> should match
// service_traits::DataType< ::panda_mover::PlannerService >
template<>
struct DataType< ::panda_mover::PlannerServiceResponse>
{
  static const char* value()
  {
    return DataType< ::panda_mover::PlannerService >::value();
  }
  static const char* value(const ::panda_mover::PlannerServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_PLANNERSERVICE_H
