// Generated by gencpp from file panda_mover/SampleService.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_SAMPLESERVICE_H
#define PANDA_MOVER_MESSAGE_SAMPLESERVICE_H

#include <ros/service_traits.h>


#include <panda_mover/SampleServiceRequest.h>
#include <panda_mover/SampleServiceResponse.h>


namespace panda_mover
{

struct SampleService
{

typedef SampleServiceRequest Request;
typedef SampleServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SampleService
} // namespace panda_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_mover::SampleService > {
  static const char* value()
  {
    return "1d1a2b8ec8f0aacf9f57d31767f2b42d";
  }

  static const char* value(const ::panda_mover::SampleService&) { return value(); }
};

template<>
struct DataType< ::panda_mover::SampleService > {
  static const char* value()
  {
    return "panda_mover/SampleService";
  }

  static const char* value(const ::panda_mover::SampleService&) { return value(); }
};


// service_traits::MD5Sum< ::panda_mover::SampleServiceRequest> should match
// service_traits::MD5Sum< ::panda_mover::SampleService >
template<>
struct MD5Sum< ::panda_mover::SampleServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::SampleService >::value();
  }
  static const char* value(const ::panda_mover::SampleServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::SampleServiceRequest> should match
// service_traits::DataType< ::panda_mover::SampleService >
template<>
struct DataType< ::panda_mover::SampleServiceRequest>
{
  static const char* value()
  {
    return DataType< ::panda_mover::SampleService >::value();
  }
  static const char* value(const ::panda_mover::SampleServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_mover::SampleServiceResponse> should match
// service_traits::MD5Sum< ::panda_mover::SampleService >
template<>
struct MD5Sum< ::panda_mover::SampleServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::SampleService >::value();
  }
  static const char* value(const ::panda_mover::SampleServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::SampleServiceResponse> should match
// service_traits::DataType< ::panda_mover::SampleService >
template<>
struct DataType< ::panda_mover::SampleServiceResponse>
{
  static const char* value()
  {
    return DataType< ::panda_mover::SampleService >::value();
  }
  static const char* value(const ::panda_mover::SampleServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_SAMPLESERVICE_H
