// Generated by gencpp from file panda_mover/StateService.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_STATESERVICE_H
#define PANDA_MOVER_MESSAGE_STATESERVICE_H

#include <ros/service_traits.h>


#include <panda_mover/StateServiceRequest.h>
#include <panda_mover/StateServiceResponse.h>


namespace panda_mover
{

struct StateService
{

typedef StateServiceRequest Request;
typedef StateServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StateService
} // namespace panda_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_mover::StateService > {
  static const char* value()
  {
    return "30fae736b7734374461e907d8c1eb052";
  }

  static const char* value(const ::panda_mover::StateService&) { return value(); }
};

template<>
struct DataType< ::panda_mover::StateService > {
  static const char* value()
  {
    return "panda_mover/StateService";
  }

  static const char* value(const ::panda_mover::StateService&) { return value(); }
};


// service_traits::MD5Sum< ::panda_mover::StateServiceRequest> should match
// service_traits::MD5Sum< ::panda_mover::StateService >
template<>
struct MD5Sum< ::panda_mover::StateServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::StateService >::value();
  }
  static const char* value(const ::panda_mover::StateServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::StateServiceRequest> should match
// service_traits::DataType< ::panda_mover::StateService >
template<>
struct DataType< ::panda_mover::StateServiceRequest>
{
  static const char* value()
  {
    return DataType< ::panda_mover::StateService >::value();
  }
  static const char* value(const ::panda_mover::StateServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_mover::StateServiceResponse> should match
// service_traits::MD5Sum< ::panda_mover::StateService >
template<>
struct MD5Sum< ::panda_mover::StateServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::StateService >::value();
  }
  static const char* value(const ::panda_mover::StateServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::StateServiceResponse> should match
// service_traits::DataType< ::panda_mover::StateService >
template<>
struct DataType< ::panda_mover::StateServiceResponse>
{
  static const char* value()
  {
    return DataType< ::panda_mover::StateService >::value();
  }
  static const char* value(const ::panda_mover::StateServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_STATESERVICE_H
