// Generated by gencpp from file panda_mover/TrainingService.msg
// DO NOT EDIT!


#ifndef PANDA_MOVER_MESSAGE_TRAININGSERVICE_H
#define PANDA_MOVER_MESSAGE_TRAININGSERVICE_H

#include <ros/service_traits.h>


#include <panda_mover/TrainingServiceRequest.h>
#include <panda_mover/TrainingServiceResponse.h>


namespace panda_mover
{

struct TrainingService
{

typedef TrainingServiceRequest Request;
typedef TrainingServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrainingService
} // namespace panda_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_mover::TrainingService > {
  static const char* value()
  {
    return "b57e415505eb1ef8a5131e05d03cd81c";
  }

  static const char* value(const ::panda_mover::TrainingService&) { return value(); }
};

template<>
struct DataType< ::panda_mover::TrainingService > {
  static const char* value()
  {
    return "panda_mover/TrainingService";
  }

  static const char* value(const ::panda_mover::TrainingService&) { return value(); }
};


// service_traits::MD5Sum< ::panda_mover::TrainingServiceRequest> should match
// service_traits::MD5Sum< ::panda_mover::TrainingService >
template<>
struct MD5Sum< ::panda_mover::TrainingServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::TrainingService >::value();
  }
  static const char* value(const ::panda_mover::TrainingServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::TrainingServiceRequest> should match
// service_traits::DataType< ::panda_mover::TrainingService >
template<>
struct DataType< ::panda_mover::TrainingServiceRequest>
{
  static const char* value()
  {
    return DataType< ::panda_mover::TrainingService >::value();
  }
  static const char* value(const ::panda_mover::TrainingServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_mover::TrainingServiceResponse> should match
// service_traits::MD5Sum< ::panda_mover::TrainingService >
template<>
struct MD5Sum< ::panda_mover::TrainingServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_mover::TrainingService >::value();
  }
  static const char* value(const ::panda_mover::TrainingServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_mover::TrainingServiceResponse> should match
// service_traits::DataType< ::panda_mover::TrainingService >
template<>
struct DataType< ::panda_mover::TrainingServiceResponse>
{
  static const char* value()
  {
    return DataType< ::panda_mover::TrainingService >::value();
  }
  static const char* value(const ::panda_mover::TrainingServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_MOVER_MESSAGE_TRAININGSERVICE_H
