#manipulator:
#  kinematics_solver: ur_kinematics/UR10KinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005

manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Distance
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.02

# manipulator:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   solve_type: Distance
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.05
#   kinematics_solver_attempts: 3
